### ISSUE TITLE
Should we add Ruby and RVM to the box?

### ISSUE THREAD

**Issue by idmontie** [gios-asu/gios-vagrant#12]
@rraub Should we add Ruby to the box?  This would make developing the gios-rails app easier if it was already all set up. I know how much of a pain that can be to get setup.

**Comment by rraub** [comment]
I dont think so, at least not yet. initially we should focus on the php side of things and after we have that all figured out and working then we can think about expanding it.

**Comment by idmontie** [comment]
But it should be added eventually, right? We can just add a milestone for that.

**Comment by rraub** [comment]
yeah eventually.

and we'll want to use [rvm](https://rvm.io/) to install and manage ruby
