### ISSUE TITLE
Can't run WordPress Multisite on ports other than 80 and 443

### ISSUE THREAD

**Issue by rraub** [gios-asu/gios-vagrant#21]
https://codex.wordpress.org/Before_You_Create_A_Network#Restrictions

so we might want to bind to port 80 and 443

**Comment by chasethenag420** [comment]
Looks to me not issue with port number as wordpress on vagrant is on 80 or 443. So issue could be with using localhost or loop back address. May be we can try with site_url, home_url to be using the vagrant network ip address instead of localhost and see if it works.

**Comment by rraub** [comment]
Further reading shows that we can't get vagrant to bind to privileged ports unless we run the whole vm as root. https://stackoverflow.com/questions/17437137/vagrant-wont-forward-only-port-80  so we need to figure out another work around.

**Comment by rraub** [comment]
This is a WordPress problem for sure, but the fact of the matter is still this vagrant box needs to be used for WordPress Multisite development. 
Another bad idea is setup nginx or apache locally and have it proxy requests to the apache ports for the vagrant machine. At this point we might as well host an entire virtualbox image with everything inside it.

**Comment by rraub** [comment]
@chasethenag420 Have you seen https://github.com/Varying-Vagrant-Vagrants/VVV ?

**Comment by chasethenag420** [comment]
Just now looked at it.. Great one pretty much everything what we need..

**Comment by rraub** [comment]
@chasethenag420 How did this issue get solved? I don't see what changes were made to address this issue or what we decided to do about it.

**Comment by chasethenag420** [comment]
We are using a plugin to update host machine hosts file to map the `dev.gios` to `192.168.160.196` a private network the vagrant file configured VB with. So once `define( 'WP_ALLOW_MULTISITE', true )` is set under wp-config.php we can use below URL to work.

`https://dev.gios/wordpress/wp-admin/`

**Comment by rraub** [comment]
I ran:

```
cd gios-vagrant
git pull origin master
vagrant reload --provision
```

Just doing a vagrant up, didn't load the new networking configuration. However my hosts file was not updated with a dev.gios entry, what plugin are you referring to? I don't see anything about that in this repo.

**Comment by chasethenag420** [comment]
Install vagrant-hostsupdater plugin with command `vagrant plugin install vagrant-hostsupdater` and then `vagrant reload --provision`

I am able to see this `Install vagrant-hostsupdater plugin with command vagrant plugin install vagrant-hostsupdate`  in documentation on master. https://github.com/gios-asu/gios-vagrant#mac

**Comment by rraub** [comment]
Cool! that did the trick. Thanks!
